### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by saifullah767** [ShingiraiBhengesa/space-travelers-hub#25]
# Github:

[Repo Link](https://github.com/ShingiraiBhengesa/space-travelers-hub.git)

[Project Link](https://github.com/ShingiraiBhengesa/space-travelers-hub/projects/1)

# Note:
There are only two people in our project.
[Shingirai](https://github.com/ShingiraiBhengesa)
[Saif Ahmed](https://github.com/Saifullah767)

**Comment by BenMukebo** [comment]
### Hi @Team,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Link to your GitHub project is present 👍🏻 
- You've provided information about the number of people in your group 👍🏻 

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Great job implementing the board by the copy of this template board: [https://github.com/microverseinc/curriculum-react-redux/projects/1](https://github.com/microverseinc/curriculum-react-redux/projects/1). However For a team with **two** people All cards with the Team3 prefix on the template must beremoved from the template, Kindly remove  *[Team3 [1pt] Create basic structure for Dragons - Setup](https://github.com/microverseinc/curriculum-react-redux/issues/49) instead you should have [1pt] Create basic structure for Missions - Setup #48 💯 😄 
- [ ] Make sure the significantly (difference >= 5 points) is more or less points than each other, kindly you need to fix it. 😉 

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mateo951** [comment]
### Hi Team, 

Your project is complete! Well done making the changes requested by the previous reviewer 🔥
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
